### ISSUE TITLE
primary.sqlite.xz changed file name

### ISSUE THREAD

**Issue by marcosw1** [GoogleCloudPlatform/compute-ansible-gluster#5]
The stackdriver_agent install attempts to download the file <https://epel.mirror.constant.com/epel/7/x86_64/repodata/6e10e58e8799b920cfa542053ef8b66181c3eea6c1c5a6ff825b155e13d14c8a-primary.sqlite.xz>.  This results in a 404 error since that file has changed names.  The new filename is <b05c65818726b68c6b158038b214e22864e77ee6f31b996842f70e4d6a3761ae-primary.sqlite.xz>.

If you are interested I can post the complete error message but it should be easy enough to reproduce.

**Comment by viglesiasce** [comment]
Thanks!

I don't think I can fix that in this repo since we are just downloading the main stackdriver install script:
https://github.com/GoogleCloudPlatform/compute-ansible-gluster/blob/master/roles/stackdriver_agent/tasks/main.yml

I'm trying to reproduce now and will see if there is anything I can do to work around it.

Thanks for the feedback.

**Comment by viglesiasce** [comment]
I was not able to reproduce this. Please post back if the error persists. I'll likely need more info to help further.
